from __future__ import annotations

from services.ai.pharmacogenomics.schema import RuleEntry


CPIC_CLOPIDOGREL_CYP2C19 = "CPIC Guideline: CYP2C19 genotype and clopidogrel therapy"
CPIC_OPIOIDS_CYP2D6 = "CPIC Guideline: CYP2D6 genotype and codeine/tramadol therapy"
CPIC_WARFARIN = "CPIC Guideline: CYP2C9, VKORC1, CYP4F2, and warfarin dosing"
CPIC_SLCO1B1_SIMVASTATIN = "CPIC Guideline: SLCO1B1 genotype and simvastatin-associated myopathy"
CPIC_THIOPURINES = "CPIC Guideline: TPMT and NUDT15 genotypes and thiopurine dosing"
CPIC_CARBAMAZEPINE_HLA = "CPIC Guideline: HLA genotype and carbamazepine/oxcarbazepine therapy"


DIPLOTYPE_PHENOTYPE: dict[str, dict[str, str]] = {
    "CYP2C19": {
        "*1/*1": "normal metabolizer",
        "*1/*2": "intermediate metabolizer",
        "*2/*1": "intermediate metabolizer",
        "*1/*3": "intermediate metabolizer",
        "*2/*2": "poor metabolizer",
        "*2/*3": "poor metabolizer",
        "*3/*3": "poor metabolizer",
        "*1/*17": "rapid metabolizer",
        "*17/*1": "rapid metabolizer",
        "*17/*17": "ultrarapid metabolizer",
        "*2/*17": "intermediate metabolizer",
        "*17/*2": "intermediate metabolizer",
    },
    "CYP2D6": {
        "*1/*1": "normal metabolizer",
        "*1/*2": "normal metabolizer",
        "*1/*4": "intermediate metabolizer",
        "*4/*1": "intermediate metabolizer",
        "*1/*5": "intermediate metabolizer",
        "*4/*4": "poor metabolizer",
        "*4/*5": "poor metabolizer",
        "*5/*5": "poor metabolizer",
        "*1XN/*1": "ultrarapid metabolizer",
        "*1/*1XN": "ultrarapid metabolizer",
        "*1X2/*1": "ultrarapid metabolizer",
        "*2XN/*1": "ultrarapid metabolizer",
        "*1/*2XN": "ultrarapid metabolizer",
    },
    "CYP2C9": {
        "*1/*1": "normal metabolizer",
        "*1/*2": "intermediate metabolizer",
        "*2/*1": "intermediate metabolizer",
        "*1/*3": "intermediate metabolizer",
        "*3/*1": "intermediate metabolizer",
        "*2/*2": "intermediate metabolizer",
        "*2/*3": "poor metabolizer",
        "*3/*2": "poor metabolizer",
        "*3/*3": "poor metabolizer",
    },
    "VKORC1": {
        "-1639 GG": "normal sensitivity",
        "-1639 G/G": "normal sensitivity",
        "GG": "normal sensitivity",
        "-1639 GA": "increased sensitivity",
        "-1639 G/A": "increased sensitivity",
        "-1639 AG": "increased sensitivity",
        "GA": "increased sensitivity",
        "AG": "increased sensitivity",
        "-1639 AA": "high sensitivity",
        "-1639 A/A": "high sensitivity",
        "AA": "high sensitivity",
    },
    "SLCO1B1": {
        "*1/*1": "normal function",
        "*1/*5": "decreased function",
        "*5/*1": "decreased function",
        "*1/*15": "decreased function",
        "*15/*1": "decreased function",
        "*5/*5": "poor function",
        "*5/*15": "poor function",
        "*15/*15": "poor function",
    },
    "TPMT": {
        "*1/*1": "normal metabolizer",
        "*1/*2": "intermediate metabolizer",
        "*2/*1": "intermediate metabolizer",
        "*1/*3A": "intermediate metabolizer",
        "*3A/*1": "intermediate metabolizer",
        "*1/*3C": "intermediate metabolizer",
        "*3C/*1": "intermediate metabolizer",
        "*2/*3A": "poor metabolizer",
        "*3A/*3A": "poor metabolizer",
        "*3A/*3C": "poor metabolizer",
        "*3C/*3C": "poor metabolizer",
    },
    "NUDT15": {
        "*1/*1": "normal metabolizer",
        "*1/*2": "intermediate metabolizer",
        "*2/*1": "intermediate metabolizer",
        "*1/*3": "intermediate metabolizer",
        "*3/*1": "intermediate metabolizer",
        "*2/*3": "poor metabolizer",
        "*3/*3": "poor metabolizer",
        "*2/*2": "poor metabolizer",
    },
    "HLA-B*15:02": {
        "positive": "positive",
        "detected": "positive",
        "present": "positive",
        "+": "positive",
        "negative": "negative",
        "not detected": "negative",
        "absent": "negative",
        "-": "negative",
    },
}


PGX_RULES: dict[tuple[str, str], dict[str, RuleEntry]] = {
    ("CYP2C19", "clopidogrel"): {
        "poor metabolizer": RuleEntry(
            clinical_implication="Reduced CYP2C19 activation of clopidogrel is expected, with decreased active metabolite exposure and reduced antiplatelet effect.",
            suggested_pharmacist_action="Discuss with prescriber whether an alternative antiplatelet such as prasugrel or ticagrelor should be considered, accounting for contraindications and indication.",
            alternatives_or_caution="Consider CPIC-guided alternative antiplatelet review; verify bleeding risk, stroke history, ACS/PCI indication, and payer/formulary constraints.",
            evidence_source=CPIC_CLOPIDOGREL_CYP2C19,
            confidence="high",
            actionable=True,
        ),
        "intermediate metabolizer": RuleEntry(
            clinical_implication="CYP2C19 activation of clopidogrel may be reduced, with lower active metabolite exposure and reduced antiplatelet effect.",
            suggested_pharmacist_action="Discuss with prescriber whether an alternative antiplatelet such as prasugrel or ticagrelor should be considered, accounting for contraindications and indication.",
            alternatives_or_caution="Consider CPIC-guided alternative antiplatelet review; verify bleeding risk, stroke history, ACS/PCI indication, and payer/formulary constraints.",
            evidence_source=CPIC_CLOPIDOGREL_CYP2C19,
            confidence="high",
            actionable=True,
        ),
        "normal metabolizer": RuleEntry(
            clinical_implication="CYP2C19 phenotype is consistent with expected clopidogrel activation for this rule.",
            suggested_pharmacist_action="Discuss with prescriber only if other clinical factors suggest antiplatelet therapy review; no PGx-based change is indicated from this rule.",
            alternatives_or_caution="Use standard clinical monitoring and verify non-genetic factors such as adherence, bleeding risk, and drug interactions.",
            evidence_source=CPIC_CLOPIDOGREL_CYP2C19,
            confidence="high",
            actionable=False,
        ),
        "rapid metabolizer": RuleEntry(
            clinical_implication="CYP2C19 phenotype is consistent with expected clopidogrel activation for this rule.",
            suggested_pharmacist_action="Discuss with prescriber only if other clinical factors suggest antiplatelet therapy review; no PGx-based change is indicated from this rule.",
            alternatives_or_caution="Use standard clinical monitoring and verify non-genetic factors such as adherence, bleeding risk, and drug interactions.",
            evidence_source=CPIC_CLOPIDOGREL_CYP2C19,
            confidence="high",
            actionable=False,
        ),
        "ultrarapid metabolizer": RuleEntry(
            clinical_implication="CYP2C19 phenotype is consistent with expected clopidogrel activation for this rule.",
            suggested_pharmacist_action="Discuss with prescriber only if other clinical factors suggest antiplatelet therapy review; no PGx-based change is indicated from this rule.",
            alternatives_or_caution="Use standard clinical monitoring and verify non-genetic factors such as adherence, bleeding risk, and drug interactions.",
            evidence_source=CPIC_CLOPIDOGREL_CYP2C19,
            confidence="high",
            actionable=False,
        ),
    },
    ("CYP2D6", "codeine"): {
        "ultrarapid metabolizer": RuleEntry(
            clinical_implication="Increased conversion of codeine to morphine can increase opioid toxicity risk.",
            suggested_pharmacist_action="Discuss with prescriber whether codeine should be avoided and whether a non-CYP2D6 analgesic should be considered.",
            alternatives_or_caution="Consider non-CYP2D6 analgesic options; verify age, respiratory risk, opioid tolerance, and concurrent CNS depressants.",
            evidence_source=CPIC_OPIOIDS_CYP2D6,
            confidence="high",
            actionable=True,
        ),
        "poor metabolizer": RuleEntry(
            clinical_implication="Little conversion of codeine to morphine is expected, which can reduce analgesia and make therapy ineffective.",
            suggested_pharmacist_action="Discuss with prescriber whether a non-CYP2D6 analgesic should be considered.",
            alternatives_or_caution="Consider analgesics not dependent on CYP2D6 activation; verify pain indication and prior response.",
            evidence_source=CPIC_OPIOIDS_CYP2D6,
            confidence="high",
            actionable=True,
        ),
        "normal metabolizer": RuleEntry(
            clinical_implication="CYP2D6 phenotype does not indicate altered codeine activation from this rule.",
            suggested_pharmacist_action="Discuss with prescriber only if other clinical factors suggest analgesic therapy review; no PGx-based change is indicated from this rule.",
            alternatives_or_caution="Use standard opioid safety monitoring and verify non-genetic risk factors.",
            evidence_source=CPIC_OPIOIDS_CYP2D6,
            confidence="high",
            actionable=False,
        ),
    },
    ("CYP2D6", "tramadol"): {
        "ultrarapid metabolizer": RuleEntry(
            clinical_implication="Increased formation of O-desmethyltramadol can increase opioid toxicity risk.",
            suggested_pharmacist_action="Discuss with prescriber whether tramadol should be avoided and whether a non-CYP2D6 analgesic should be considered.",
            alternatives_or_caution="Consider non-CYP2D6 analgesic options; verify seizure risk, serotonin syndrome risk, renal function, and concurrent CNS depressants.",
            evidence_source=CPIC_OPIOIDS_CYP2D6,
            confidence="high",
            actionable=True,
        ),
        "poor metabolizer": RuleEntry(
            clinical_implication="Reduced formation of O-desmethyltramadol is expected, which can reduce analgesia and make therapy ineffective.",
            suggested_pharmacist_action="Discuss with prescriber whether a non-CYP2D6 analgesic should be considered.",
            alternatives_or_caution="Consider analgesics not dependent on CYP2D6 activation; verify pain indication, seizure risk, serotonin syndrome risk, and prior response.",
            evidence_source=CPIC_OPIOIDS_CYP2D6,
            confidence="high",
            actionable=True,
        ),
        "normal metabolizer": RuleEntry(
            clinical_implication="CYP2D6 phenotype does not indicate altered tramadol activation from this rule.",
            suggested_pharmacist_action="Discuss with prescriber only if other clinical factors suggest analgesic therapy review; no PGx-based change is indicated from this rule.",
            alternatives_or_caution="Use standard opioid safety monitoring and verify non-genetic risk factors.",
            evidence_source=CPIC_OPIOIDS_CYP2D6,
            confidence="high",
            actionable=False,
        ),
    },
    ("CYP2C9", "warfarin"): {
        "intermediate metabolizer": RuleEntry(
            clinical_implication="Reduced CYP2C9 metabolism can increase warfarin exposure and bleeding risk at typical starting doses.",
            suggested_pharmacist_action="Discuss with prescriber whether a lower starting dose, more frequent INR monitoring, or a validated CPIC-supported dosing algorithm should be considered.",
            alternatives_or_caution="Consider genotype-guided warfarin dosing with clinical factors; verify indication, target INR, interacting drugs, diet, age, and bleeding history.",
            evidence_source=CPIC_WARFARIN,
            confidence="high",
            actionable=True,
        ),
        "poor metabolizer": RuleEntry(
            clinical_implication="Markedly reduced CYP2C9 metabolism can increase warfarin exposure and bleeding risk at typical starting doses.",
            suggested_pharmacist_action="Discuss with prescriber whether a lower starting dose, more frequent INR monitoring, or a validated CPIC-supported dosing algorithm should be considered.",
            alternatives_or_caution="Consider genotype-guided warfarin dosing with clinical factors; verify indication, target INR, interacting drugs, diet, age, and bleeding history.",
            evidence_source=CPIC_WARFARIN,
            confidence="high",
            actionable=True,
        ),
        "normal metabolizer": RuleEntry(
            clinical_implication="CYP2C9 phenotype does not indicate reduced warfarin metabolism from this rule.",
            suggested_pharmacist_action="Discuss with prescriber only if clinical factors suggest warfarin dose review; no PGx-based change is indicated from this CYP2C9 rule.",
            alternatives_or_caution="Warfarin dosing still requires INR monitoring and assessment of clinical and drug-interaction factors.",
            evidence_source=CPIC_WARFARIN,
            confidence="high",
            actionable=False,
        ),
    },
    ("VKORC1", "warfarin"): {
        "increased sensitivity": RuleEntry(
            clinical_implication="VKORC1 genotype is associated with increased warfarin sensitivity and increased bleeding risk at typical starting doses.",
            suggested_pharmacist_action="Discuss with prescriber whether a lower starting dose, more frequent INR monitoring, or a validated CPIC-supported dosing algorithm should be considered.",
            alternatives_or_caution="Consider genotype-guided warfarin dosing with clinical factors; verify indication, target INR, interacting drugs, diet, age, and bleeding history.",
            evidence_source=CPIC_WARFARIN,
            confidence="high",
            actionable=True,
        ),
        "high sensitivity": RuleEntry(
            clinical_implication="VKORC1 genotype is associated with high warfarin sensitivity and increased bleeding risk at typical starting doses.",
            suggested_pharmacist_action="Discuss with prescriber whether a lower starting dose, more frequent INR monitoring, or a validated CPIC-supported dosing algorithm should be considered.",
            alternatives_or_caution="Consider genotype-guided warfarin dosing with clinical factors; verify indication, target INR, interacting drugs, diet, age, and bleeding history.",
            evidence_source=CPIC_WARFARIN,
            confidence="high",
            actionable=True,
        ),
        "normal sensitivity": RuleEntry(
            clinical_implication="VKORC1 phenotype does not indicate increased warfarin sensitivity from this rule.",
            suggested_pharmacist_action="Discuss with prescriber only if clinical factors suggest warfarin dose review; no PGx-based change is indicated from this VKORC1 rule.",
            alternatives_or_caution="Warfarin dosing still requires INR monitoring and assessment of clinical and drug-interaction factors.",
            evidence_source=CPIC_WARFARIN,
            confidence="high",
            actionable=False,
        ),
    },
    ("SLCO1B1", "simvastatin"): {
        "decreased function": RuleEntry(
            clinical_implication="Reduced SLCO1B1 transporter function can increase simvastatin exposure and myopathy risk.",
            suggested_pharmacist_action="Discuss with prescriber whether a lower simvastatin dose or an alternative statin should be considered.",
            alternatives_or_caution="Consider lower-risk statin options and verify dose, interacting drugs, prior muscle symptoms, CK history, and ASCVD indication.",
            evidence_source=CPIC_SLCO1B1_SIMVASTATIN,
            confidence="high",
            actionable=True,
        ),
        "poor function": RuleEntry(
            clinical_implication="Poor SLCO1B1 transporter function can substantially increase simvastatin exposure and myopathy risk.",
            suggested_pharmacist_action="Discuss with prescriber whether a lower simvastatin dose or an alternative statin should be considered.",
            alternatives_or_caution="Consider lower-risk statin options and verify dose, interacting drugs, prior muscle symptoms, CK history, and ASCVD indication.",
            evidence_source=CPIC_SLCO1B1_SIMVASTATIN,
            confidence="high",
            actionable=True,
        ),
        "normal function": RuleEntry(
            clinical_implication="SLCO1B1 phenotype does not indicate increased simvastatin myopathy risk from this rule.",
            suggested_pharmacist_action="Discuss with prescriber only if other clinical factors suggest statin therapy review; no PGx-based change is indicated from this rule.",
            alternatives_or_caution="Use standard statin monitoring and verify non-genetic myopathy risk factors.",
            evidence_source=CPIC_SLCO1B1_SIMVASTATIN,
            confidence="high",
            actionable=False,
        ),
    },
    ("TPMT", "thiopurines"): {
        "intermediate metabolizer": RuleEntry(
            clinical_implication="Reduced TPMT activity can increase thiopurine active metabolite exposure and myelosuppression risk.",
            suggested_pharmacist_action="Discuss with prescriber whether a reduced thiopurine starting dose and close blood-count monitoring should be considered.",
            alternatives_or_caution="Consider CPIC-guided dose reduction; verify indication, target dose, concurrent allopurinol/febuxostat, and baseline CBC.",
            evidence_source=CPIC_THIOPURINES,
            confidence="high",
            actionable=True,
        ),
        "poor metabolizer": RuleEntry(
            clinical_implication="Absent or markedly reduced TPMT activity can cause severe thiopurine myelosuppression at conventional doses.",
            suggested_pharmacist_action="Discuss with prescriber whether a drastically reduced thiopurine dose or a non-thiopurine alternative should be considered.",
            alternatives_or_caution="Consider specialist-guided dosing or alternatives; verify indication, concurrent xanthine oxidase inhibitors, and baseline CBC.",
            evidence_source=CPIC_THIOPURINES,
            confidence="high",
            actionable=True,
        ),
        "normal metabolizer": RuleEntry(
            clinical_implication="TPMT phenotype does not indicate increased thiopurine myelosuppression risk from this TPMT rule.",
            suggested_pharmacist_action="Discuss with prescriber only if clinical factors suggest thiopurine therapy review; no PGx-based change is indicated from this TPMT rule.",
            alternatives_or_caution="Thiopurines still require routine CBC and liver-function monitoring.",
            evidence_source=CPIC_THIOPURINES,
            confidence="high",
            actionable=False,
        ),
    },
    ("NUDT15", "thiopurines"): {
        "intermediate metabolizer": RuleEntry(
            clinical_implication="Reduced NUDT15 activity can increase thiopurine sensitivity and myelosuppression risk.",
            suggested_pharmacist_action="Discuss with prescriber whether a reduced thiopurine starting dose and close blood-count monitoring should be considered.",
            alternatives_or_caution="Consider CPIC-guided dose reduction; verify indication, ancestry-informed risk, and baseline CBC.",
            evidence_source=CPIC_THIOPURINES,
            confidence="high",
            actionable=True,
        ),
        "poor metabolizer": RuleEntry(
            clinical_implication="Absent or markedly reduced NUDT15 activity can cause severe thiopurine myelosuppression at conventional doses.",
            suggested_pharmacist_action="Discuss with prescriber whether a drastically reduced thiopurine dose or a non-thiopurine alternative should be considered.",
            alternatives_or_caution="Consider specialist-guided dosing or alternatives; verify indication, ancestry-informed risk, and baseline CBC.",
            evidence_source=CPIC_THIOPURINES,
            confidence="high",
            actionable=True,
        ),
        "normal metabolizer": RuleEntry(
            clinical_implication="NUDT15 phenotype does not indicate increased thiopurine myelosuppression risk from this NUDT15 rule.",
            suggested_pharmacist_action="Discuss with prescriber only if clinical factors suggest thiopurine therapy review; no PGx-based change is indicated from this NUDT15 rule.",
            alternatives_or_caution="Thiopurines still require routine CBC and liver-function monitoring.",
            evidence_source=CPIC_THIOPURINES,
            confidence="high",
            actionable=False,
        ),
    },
    ("HLA-B*15:02", "carbamazepine"): {
        "positive": RuleEntry(
            clinical_implication="HLA-B*15:02 positivity is associated with high risk of carbamazepine-induced Stevens-Johnson syndrome/toxic epidermal necrolysis.",
            suggested_pharmacist_action="Discuss with prescriber whether carbamazepine should be avoided and whether an alternative not associated with this HLA risk should be considered.",
            alternatives_or_caution="Oxcarbazepine has related HLA-B*15:02 caution in CPIC; verify ancestry, prior exposure, indication, and alternative therapy options.",
            evidence_source=CPIC_CARBAMAZEPINE_HLA,
            confidence="high",
            actionable=True,
        ),
        "negative": RuleEntry(
            clinical_implication="HLA-B*15:02 negativity does not indicate elevated SJS/TEN risk from this HLA-B*15:02 rule.",
            suggested_pharmacist_action="Discuss with prescriber only if other clinical factors suggest carbamazepine therapy review; no PGx-based change is indicated from this rule.",
            alternatives_or_caution="Negative HLA-B*15:02 does not rule out all hypersensitivity risk; verify other HLA results, ancestry, and clinical history.",
            evidence_source=CPIC_CARBAMAZEPINE_HLA,
            confidence="high",
            actionable=False,
        ),
    },
}
